FROM python:3.11-slim

WORKDIR /app

# System dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    default-libmysqlclient-dev \
    pkg-config \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install mysqlclient gunicorn

# Copy project
COPY . .

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

EXPOSE 8000

CMD sh -c "\
until nc -z $DB_HOST 3306; do \
  echo 'Waiting for MySQL...'; \
  sleep 3; \
done && \
python manage.py migrate && \
python manage.py collectstatic --noinput && \
gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000 --workers 3"
